### ISSUE TITLE
Select Attributes for Import

### ISSUE THREAD

**Issue by lukebd** [akeneo/magento2-connector-community#282]
It would be beneficial to be able to select which attributes get imported from Akeneo to Magento. As Akeneo is the master of data I would want Akeneo to have all attributes relating to a product but on Magento such attributes may not be required as they are not currently used in product description or layered navigation. With all attributes being sent from Akeneo to Magento we have had to limit the total attributes we have on Akeneo to ensure the Magento indexers can handle the data efficiently.

**Comment by Melleschepers** [comment]
Totally agree. Would be a great beneficial since we also have a lot unnecessary attributes (with a lot of values) in our magento database. I was thinking something like below (exclude the attributes you DON'T WANT to import) would be good... but maybe it's indeed better to select which attributes you WANT to import (besides the default ones) for also running automatically (cron) imports.

![image](https://user-images.githubusercontent.com/13859086/101246150-bf657080-3711-11eb-9649-4279b2b8ccca.png)

**Comment by Dnd-Gimix** [comment]
Hello @Melleschepers @lukebd ,

Thank you for your interest in Akeneo Connector.

We were already working on it, and your prayers has been answered in the latest 101.1.1 version of the connector : https://github.com/akeneo/magento2-connector-community/releases/tag/v101.1.1

You can now filter the attributes by selecting the one you want to import and not synchronize every single one of them. This will also filter your option and product job API call and restrict the call to only attributes you want to import, and optimize the job.

Careful : this has been made available by API improvements on Akeneo side, only available for Akeneo 4.0.62 or greater or Serenity. If you upgrade your connector, make sure to configure correctly the newest "Akeneo Edition" field in the configuration and check the latest release notes: https://github.com/akeneo/magento2-connector-community/releases

Have a good day.

Regards,

**Comment by Melleschepers** [comment]
Wh00h000! That's a nice christmas gift! I will test this feature in the upcoming days 👍

**Comment by Dnd-Gimix** [comment]
Hello @Melleschepers @lukebd ,

As this feature has been released, I'll close the issue.
Have a good day !

Regards
