### ISSUE TITLE
Completeness filter operator does not get replaced by real operator in some case

### ISSUE THREAD

**Issue by bartoszkubicki** [akeneo/magento2-connector-community#50]
### Environment and configuration

1. Akeneo connecto 100.2.2

### Steps to reproduce

1. Set in configuration completness filter as greater or equals on all locales

### Expected result

1. Operator gets replaced by some real operator
2. With this data replaced it is sent to  Akeneo

### Actual result

1. It is not replaced by real operator

By the way if someone can tell what is best configuration of this filter to get only products 100% complete on each channel and locales, please let me know or writ it here.

**Comment by Dnd-Gimix** [comment]
Hello @bartoszkubicki ,

Thank you for your interest in Akeneo Connector.

Could you be more specific on this statement : "Operator gets replaced by some real operator"
Which operator is replaced and what is the "real operator" in your case ?
Could you also provide a screenshot of your filter configuration please ?

If you just need to get product with completeness at 100%, you just have to configure the following fields in the filter section : 
- Completeness type : Equals
- Completeness value : 100

It will fetch only products with 100% completeness.

Regards,

**Comment by bartoszkubicki** [comment]
Here you have screenshot from xdebug - as you can see it is after api call:
![image](https://user-images.githubusercontent.com/20238194/66699633-d9abe600-ece8-11e9-8814-5900c7dc139c.png)
 Moreover here you have url just after calling product api:
`http://test.loc/api/rest/v1/products?page=1&with_count=false&pagination_type=page&limit=1&search=%7B%22completeness%22%3A%5B%7B%22operator%22%3A%22GREATER%20OR%20EQUALS%20THAN%20ON%20ALL%20LOCALES%22%2C%22value%22%3A%22100%22%2C%22scope%22%3A%22ecommerce%22%2C%22locales%22%3A%5B%22cs_CZ%22%2C%22en_US%22%2C%22hu_HU%22%2C%22lt_LT%22%2C%22pl_PL%22%2C%22ro_RO%22%2C%22sk_SK%22%5D%7D%5D%2C%22enabled%22%3A%5B%7B%22operator%22%3A%22%3D%22%2C%22value%22%3Atrue%7D%5D%7D&scope=ecommerce&locales=en_US%2Cpl_PL`

and decoded one:

`http://test.loc/api/rest/v1/products?page=1&with_count=false&pagination_type=page&limit=1&search={"completeness":[{"operator":"GREATER OR EQUALS THAN ON ALL LOCALES","value":"100","scope":"ecommerce","locales":["cs_CZ","en_US","hu_HU","lt_LT","pl_PL","ro_RO","sk_SK"]}],"enabled":[{"operator":"=","value":true}]}&scope=ecommerce&locales=en_US,pl_PL`

**Comment by Dnd-Gimix** [comment]
Hello @bartoszkubicki ,

Thank you for your feedback.

Despite the informations you provided, I still cannot understand the issue here.
Could you please point precisely what is not correct in the decoded URL you gave us above : 
http://test.loc/api/rest/v1/products?page=1&with_count=false&pagination_type=page&limit=1&search={"completeness":[{"operator":"GREATER OR EQUALS THAN ON ALL LOCALES","value":"100","scope":"ecommerce","locales":["cs_CZ","en_US","hu_HU","lt_LT","pl_PL","ro_RO","sk_SK"]}],"enabled":[{"operator":"=","value":true}]}&scope=ecommerce&locales=en_US,pl_PL

And also provide us what should be the actual result please ?
Based on : https://api.akeneo.com/documentation/filter.html#on-their-completeness

Many thanks !

Regards,

**Comment by bartoszkubicki** [comment]
Ok, I have taken it as bug, because other operators got replaced. I am sorry, this issue can be closed.
