### ISSUE TITLE
Stock qty

### ISSUE THREAD

**Issue by ibs83278** [akeneo/magento2-connector-community#562]
I know that updating product´s stock quantity using the connector is not recommended as described in
https://help.akeneo.com/magento2-connector/articles/what-data.html 

But for me, in a special project there are some good reasons to do exactly this, so my simple question:  is it possible or not?

Thanks!

**Comment by oefterdal** [comment]
@ibs83278 As far as I know the connector hasn’t implemented stock and stock is not an attribute you can easily just map anymore in later Magento releases because of the new inventory implementation (MSI). If I was you I would implement an server less function that pass the stock data from Akeneo (if you have to have it there) and post it to `/V1/inventory/source-items` You could use Akeneo’s event api to call the server less function. 

https://magento.redoc.ly/2.4.4-admin/tag/inventorysource-items#operation/inventoryApiSourceItemsSaveV1ExecutePost

https://api.akeneo.com/events-documentation/overview.html

**Comment by ibs83278** [comment]
@oefterdal Thanks for your reply. I think you are right and the approach you describe sounds interesting. I will give it a try.
