### ISSUE TITLE
array_key_exists() expects parameter 2 to be array

### ISSUE THREAD

**Issue by alex5513** [akeneo/magento2-connector-community#81]
Bonjour,

J'ai une erreur php dans la fonction formatValues() de Helper/Import/Product.php car dans la boucle ligne 141 je n'ai pas toujours un array.

Serait-il possible d'ajouter un test sur price pour vérifier si c'est un array ?

![Capture d’écran 2019-11-19 à 18 26 17](https://user-images.githubusercontent.com/6359584/69170311-2eb5f580-0afa-11ea-82eb-0711a15c74ae.png)
![Capture d’écran 2019-11-19 à 18 22 43](https://user-images.githubusercontent.com/6359584/69170313-2f4e8c00-0afa-11ea-921e-555ee9a14efa.png)

Cordialement

Alexis

**Comment by bartoszkubicki** [comment]
Hi alex,

It is github, english is main language here. Your issue can help other developers, so please translate it.

**Comment by leon-fb** [comment]
We had this exact issue; for now we resolved it by:

[magento_root]/vendor/akeneo/module-magento2-connector-community/Helper/Import/Product.php on line 142

The if condition needs to be(come):
-----------------------------------
if (!is_array($price) || !array_key_exists('currency', $price) || !array_key_exists('amount', $price)) {
-----------------------------------
Instead of:
-----------------------------------
if (!array_key_exists('currency', $price) || !array_key_exists('amount', $price)) {
-----------------------------------

**Comment by Dnd-Gimix** [comment]
Hello @alex5513 @leon-fb @bartoszkubicki ,

We have released @leon-fb fix in the latest 100.3.3 version of the connector.
Please, come back to us to confirm that it solved your issue.

Regards,

**Comment by Dnd-Gimix** [comment]
As the fix is released, I'll close the issue.
